# git

alias ga="git add -u"
alias gb="git branch"
alias gc="git commit"
alias gck="git checkout"
alias gp="git pull"
alias gpl="git pull"
alias gs="git status"

# misc

alias ..="cd .."
alias la="ls -la"
